### ISSUE TITLE
Latest version of `highcharts` and `highcharts-react-official` gives compilation error

### ISSUE THREAD

**Issue by valdemarrolfsen** [highcharts/highcharts-react#132]
Upgraded to the latest version of `highcharts` and `highcharts-react-official` and received the following error:

```
./node_modules/highcharts-react-official/dist/highcharts-react.min.js
Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/React/react'.
```

React version: 16.6.3

Link to sandbox for reproduction: 
https://codesandbox.io/embed/holy-smoke-u4x4s

Any idea what causes this?

**Comment by Denyllon** [comment]
Hi @valdemarrolfsen ,

Thank you for reporting the issue.
Definitely, it's the bug related with incorrect webpack configuration after last release. It should be fixed immediately.

Kind regards!

**Comment by jonathan-daniel** [comment]
hello,

is this fixed on the master branch? on npm I still get this error.

**Comment by nvdbleek** [comment]
@Denyllon `/dist/highcharts-react.min.js` of v2.2.1 still seems to have `module.exports=t(require("React"))` and this is causing the problem I think. /cc @jonathan-daniel
